# Generated by Django 4.2.6 on 2023-11-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopCoronaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('region', models.CharField(max_length=255)),
                ('hospitalized', models.IntegerField()),
                ('infected', models.IntegerField()),
                ('recovered', models.IntegerField()),
                ('deaths', models.IntegerField()),
            ],
            options={
                'unique_together': {('start_date', 'end_date', 'region')},
            },
        ),
    ]
