# Generated by Django 4.2.6 on 2023-12-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0003_externaldatabasestatistic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdata',
            name='cases',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='days_14_cases_per_100000',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='deaths',
            field=models.IntegerField(null=True),
        ),
    ]
