# Generated by Django 4.2.6 on 2023-12-13 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0004_alter_csvdata_cases_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvdata',
            old_name='days_14_cases_per_100000',
            new_name='per_100000_cases_for_2_weeks',
        ),
    ]
