# Generated by Django 4.2.6 on 2023-12-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0005_rename_days_14_cases_per_100000_csvdata_per_100000_cases_for_2_weeks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdata',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
