# Generated by Django 4.2.6 on 2023-12-13 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0006_alter_csvdata_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GogovRegionData',
        ),
    ]
