# Generated by Django 4.2.6 on 2023-12-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0007_delete_gogovregiondata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='externaldatabasestatistic',
            table='covid',
        ),
        migrations.AlterModelTable(
            name='externaldatabasevaccination',
            table='vactination',
        ),
        migrations.CreateModel(
            name='RegionTransformedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('region', models.TextField()),
                ('weekly_infected', models.IntegerField(blank=True, null=True)),
                ('weekly_deaths', models.IntegerField(blank=True, null=True)),
                ('weekly_recovered', models.IntegerField(blank=True, null=True)),
                ('infected', models.IntegerField(blank=True, null=True)),
                ('deaths', models.IntegerField(blank=True, null=True)),
                ('recovered', models.IntegerField(blank=True, null=True)),
                ('first_component', models.IntegerField(blank=True, null=True)),
                ('second_component', models.IntegerField(blank=True, null=True)),
                ('weekly_infected_per_100000', models.FloatField(blank=True, null=True)),
                ('weekly_deaths_per_100000', models.FloatField(blank=True, null=True)),
                ('weekly_recovered_per_100000', models.FloatField(blank=True, null=True)),
                ('infected_per_100000', models.FloatField(blank=True, null=True)),
                ('deaths_per_100000', models.FloatField(blank=True, null=True)),
                ('recovered_per_100000', models.FloatField(blank=True, null=True)),
                ('weekly_recovered_infected_ratio', models.FloatField(blank=True, null=True)),
                ('weekly_deaths_infected_ratio', models.FloatField(blank=True, null=True)),
                ('weekly_vaccinations_infected_ratio', models.FloatField(blank=True, null=True)),
                ('vaccinations_population_ratio', models.FloatField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('start_date', 'end_date', 'region')},
            },
        ),
        migrations.CreateModel(
            name='GlobalTransformedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('weekly_infected', models.IntegerField(blank=True, null=True)),
                ('weekly_deaths', models.IntegerField(blank=True, null=True)),
                ('weekly_recovered', models.IntegerField(blank=True, null=True)),
                ('infected', models.IntegerField(blank=True, null=True)),
                ('deaths', models.IntegerField(blank=True, null=True)),
                ('recovered', models.IntegerField(blank=True, null=True)),
                ('first_component', models.IntegerField(blank=True, null=True)),
                ('second_component', models.IntegerField(blank=True, null=True)),
                ('weekly_infected_per_100000', models.FloatField(blank=True, null=True)),
                ('weekly_deaths_per_100000', models.FloatField(blank=True, null=True)),
                ('weekly_recovered_per_100000', models.FloatField(blank=True, null=True)),
                ('infected_per_100000', models.FloatField(blank=True, null=True)),
                ('deaths_per_100000', models.FloatField(blank=True, null=True)),
                ('recovered_per_100000', models.FloatField(blank=True, null=True)),
                ('weekly_recovered_infected_ratio', models.FloatField(blank=True, null=True)),
                ('weekly_deaths_infected_ratio', models.FloatField(blank=True, null=True)),
                ('weekly_vaccinations_infected_ratio', models.FloatField(blank=True, null=True)),
                ('vaccinations_population_ratio', models.FloatField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('start_date', 'end_date')},
            },
        ),
    ]
