# Generated by Django 4.2.6 on 2023-12-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0008_alter_externaldatabasestatistic_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globaltransformeddata',
            name='weekly_first_component',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globaltransformeddata',
            name='weekly_second_component',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globaltransformeddata',
            name='weekly_vaccinations',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
