# Generated by Django 4.2.6 on 2023-12-24 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0009_globaltransformeddata_weekly_first_component_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gogovglobaldata',
            old_name='full_vaccinated',
            new_name='second_component',
        ),
    ]
