# Generated by Django 4.2.6 on 2024-01-02 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0011_remove_regiontransformeddata_first_component_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gogovglobaldata',
            name='children_vaccinated',
        ),
        migrations.RemoveField(
            model_name='gogovglobaldata',
            name='need_revaccination',
        ),
        migrations.RemoveField(
            model_name='gogovglobaldata',
            name='revaccinated',
        ),
    ]
