# Generated by Django 4.2.6 on 2024-01-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0013_remove_gogovglobaldata_children_vaccinated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
