# Generated by Django 4.2.6 on 2024-01-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0014_alter_region_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('region', models.TextField()),
                ('population', models.IntegerField()),
            ],
            options={
                'unique_together': {('year', 'region')},
            },
        ),
    ]
