version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGUSER: ${DB_USER}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  external_postgres:
    image: freakingjackpot/etl_project:external_database
    restart: always
    environment:
      POSTGRES_USER: ${EXTERNAL_DB_USER}
      POSTGRES_PASSWORD: ${EXTERNAL_DB_PASS}
      POSTGRES_DB: ${EXTERNAL_DB_NAME}
    ports:
      - 5433:5433

  web:
    build: .
    container_name: web
    command: uvicorn covid_dashboard.asgi:application --host 0.0.0.0 --port 8000
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/static
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DJANGO_CSRF_TRUSTED_ORIGINS: ${DJANGO_CSRF_TRUSTED_ORIGINS}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      GRAYLOG_HTTP_ENDPOINT_PORT: ${GRAYLOG_HTTP_ENDPOINT_PORT}
      GRAYLOG_HTTP_ENDPOINT_IP: ${GRAYLOG_HTTP_ENDPOINT_IP}

    depends_on:
      - postgres

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
    environment:
      GRAYLOG_IP: ${GRAYLOG_HTTP_ENDPOINT_IP}
    ports:
      - 1337:80
    depends_on:
      - web

  mongo:
    image: mongo:5.0.13
    volumes:
      - mongo_data:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true -Xms512m -Xmx512m"

  graylog:
    image: graylog/graylog:5.0
    volumes:
      - graylog_data:/usr/share/graylog/data
    environment:
      GRAYLOG_PASSWORD_SECRET: ${GRAYLOG_PASSWORD_SECRET}
      GRAYLOG_HTTP_EXTERNAL_URI: ${GRAYLOG_HTTP_EXTERNAL_URI}
      GRAYLOG_ROOT_PASSWORD_SHA2: ${GRAYLOG_ROOT_PASSWORD_SHA2}
      GRAYLOG_HTTP_ENDPOINT: ${GRAYLOG_HTTP_ENDPOINT}
    restart: always
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # GELF HTTP
      - 12201:12201
volumes:
  postgres_data:
  static_volume:
  mongo_data:
  es_data:
  graylog_data:
