# Generated by Django 4.2.6 on 2023-11-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('cases', models.IntegerField(default=True)),
                ('deaths', models.IntegerField(default=True)),
                ('days_14_cases_per_100000', models.FloatField(blank=True, default=True, null=True)),
            ],
        ),
    ]
