# Generated by Django 4.2.6 on 2023-11-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0002_stopcoronadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDatabaseStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('region', models.CharField(max_length=255)),
                ('infection', models.BigIntegerField()),
                ('recovery', models.BigIntegerField()),
                ('death', models.BigIntegerField()),
                ('death_per_day', models.IntegerField()),
                ('infection_per_day', models.IntegerField()),
                ('recovery_per_day', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalDatabaseVaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_vaccinations', models.BigIntegerField()),
                ('people_vaccinated', models.BigIntegerField()),
                ('people_fully_vaccinated', models.BigIntegerField()),
                ('total_boosters', models.BigIntegerField()),
                ('daily_vaccinations_raw', models.BigIntegerField()),
                ('daily_vaccinations', models.BigIntegerField()),
                ('total_vaccinations_per_hundred', models.FloatField()),
                ('people_vaccinated_per_hundred', models.FloatField()),
                ('people_fully_vaccinated_per_hundred', models.FloatField()),
                ('total_boosters_per_hundred', models.FloatField()),
                ('daily_vaccinations_per_million', models.BigIntegerField()),
                ('daily_people_vaccinated', models.BigIntegerField()),
                ('daily_people_vaccinated_per_hundred', models.FloatField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GogovGlobalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('first_component', models.IntegerField()),
                ('full_vaccinated', models.IntegerField()),
                ('children_vaccinated', models.IntegerField()),
                ('revaccinated', models.IntegerField()),
                ('need_revaccination', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GogovRegionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField()),
                ('date', models.DateField()),
                ('vaccinated', models.IntegerField()),
                ('avg_people_per_day', models.IntegerField()),
                ('full_vaccinated', models.IntegerField()),
                ('revaccinated', models.IntegerField()),
                ('need_revaccination', models.IntegerField()),
                ('children_vaccinated', models.IntegerField()),
            ],
            options={
                'unique_together': {('region', 'date')},
            },
        ),
    ]
