alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: "web"
    scrape_interval: 30s
    static_configs:
      - targets:
          - web:8000

  - job_name: "prometheus"
    scrape_interval: 30s
    static_configs:
      - targets:
          - localhost:9090

  - job_name: "node"
    scrape_interval: 30s
    static_configs:
      - targets:
          - node-exporter:9100

  - job_name: "nginx"
    scrape_interval: 30s
    static_configs:
      - targets:
          - nginx-exporter:9113

  - job_name: "postgres"
    scrape_interval: 30s
    static_configs:
      - targets:
          - postgres-exporter:9187

  - job_name: "cadvisor"
    scrape_interval: 5s
    static_configs:
      - targets:
          - cadvisor:8080
    basic_auth:
      username: admin
      password: admin

  - job_name: "promtail"
    scrape_interval: 30s
    static_configs:
      - targets:
          - promtail:9080

  - job_name: "loki"
    scrape_interval: 30s
    static_configs:
      - targets:
          - loki:3100

  - job_name: 'statsd-exporter'
    static_configs:
      - targets: [ 'airflow-statsd-exporter:9102' ]
