alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: "web"
    scrape_interval: 30s
    static_configs:
      - targets:
          - web:8000

  - job_name: "prometheus"
    scrape_interval: 30s
    static_configs:
      - targets:
          - localhost:9090

  - job_name: "node"
    scrape_interval: 30s
    static_configs:
      - targets:
          - node-exporter:9100

  - job_name: "nginx"
    scrape_interval: 30s
    static_configs:
      - targets:
          - nginx-exporter:9113

  - job_name: "postgres"
    scrape_interval: 30s
    static_configs:
      - targets:
          - postgres-exporter:9187

  - job_name: "cadvisor"
    scrape_interval: 5s
    static_configs:
      - targets:
          - cadvisor:8080
    basic_auth:
      username: admin
      password: admin

  - job_name: "promtail"
    scrape_interval: 30s
    static_configs:
      - targets:
          - promtail:9080

  - job_name: "loki"
    scrape_interval: 30s
    static_configs:
      - targets:
          - loki:3100

  - job_name: "website-monitoring-http"
    metrics_path: /probe
    params:
      module: [ http_2xx ]
    static_configs:
      - targets:
          - http://localhost:1337
          - https://localhost:1337

    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: "website-monitoring-icmp"
    metrics_path: /probe
    params:
      module: [ icmp ]
    static_configs:
      - targets:
          - http://localhost:1337
          - https://localhost:1337
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
