apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: false
    editable: true

  - name: Loki
    type: loki
    access: proxy
    basicAuth: false
    url: http://loki:3100
    isDefault: false
    editable: true
    jsonData:
      derivedFields:
        - datasourceUid: my-jaeger
          name: TraceID
          matcherRegex: trace_id=(\w+)
          url: '$${__value.raw}'
        - name: TraceID
          matcherRegex: trace_id=(\w+)
          url: 'http://localhost:16686/trace/$${__value.raw}'

  - name: jaeger
    type: jaeger
    uid: my-jaeger
    access: browser
    url: http://jaeger:16686
    isDefault: false
    version: 1
    editable: true
    basicAuth: false
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: my-loki
        tags: [ ]
        mappedTags: [ { key: 'service.name', value: 'app' } ]
        mapTagNamesEnabled: true