{
 "title": "Logs",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "filter" },
   {
    "name": "containers",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Containers logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container=~\"$containers\"}"
    }
   ]
  },
  {
   "title": "Django logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{host=\"web\"} |= `$filter`"
    }
   ]
  },
  {
   "title": "Nginx requests logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"nginx\"} |= `$filter`"
    }
   ]
  }
 ]
}