# Generated by Django 4.2.6 on 2024-01-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetinfo',
            name='model_name',
            field=models.TextField(choices=[('INVL', 'Invalid'), ('GlobalTransformedData', 'GlobalTransformedData'), ('RegionTransformedData', 'RegionTransformedData')], default='INVL'),
        ),
        migrations.AlterUniqueTogether(
            name='datasetinfo',
            unique_together={('dataset_name', 'model_name')},
        ),
    ]
